---
:github_organization: ManageIQ
:scan_default_repos: true
:number_of_days_selection: 7
:sprint_length_in_weeks: 2
:sprint_end_day: monday
:additional_repos: []
:excluded_repos:
- ManageIQ/handsoap
- ManageIQ/sprint_statistics
- ManageIQ/integration_tests
- ManageIQ/guides
:priority:
- :prefix: E
  :label: enhancement
- :prefix: B
  :label: bug
- :prefix: T
  :label: technical debt
- :prefix: R
  :label: refactoring
:filters:
  :enabled: false
  :users: []
  :labels: []
  :non_filtered_repos: []
