---
:github_organization: ManageIQ
:milestone_reference_repo: ManageIQ/manageiq
:additional_repos: []
:excluded_repos:
- ManageIQ/integration_tests
- ManageIQ/manageiq-appliance-dev-setup
- ManageIQ/manageiq-performance
- ManageIQ/manageiq-release
- ManageIQ/manageiq-vagrant-dev
- ManageIQ/miq_tools_services
- ManageIQ/polisher
- ManageIQ/sprint_statistics
- ManageIQ/wrapanapi
:priority:
- :prefix: E
  :label: enhancement
- :prefix: B
  :label: bug
- :prefix: T
  :label: technical debt
- :prefix: R
  :label: refactoring
:filters:
  :users: []
  :labels: []
  :non_filtered_repos: []
